apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vocalog-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/diva-eng/vocalog-service.git
    targetRevision: HEAD
    path: charts/vocalog-server
  destination:
    server: https://kubernetes.default.svc
    namespace: vocalog-server
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
