apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vocalog-server-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/diva-eng/vocalog-service.git
    targetRevision: HEAD
    path: charts/vocalog-server-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: vocalog-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 1m
        maxDuration: 16m
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
