apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-password-externalsecret
  namespace: vocalog-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-clustersecretstore
  target:
    name: mongo-password-secret
  data:
    - secretKey: mongodb-password
      remoteRef:
        key: mongo-password
    - secretKey: mongodb-root-password
      remoteRef:
        key: mongo-password
