image:
  repository: crccheck/hello-world
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8000

ingress:
  main:
    enabled: true
    annotations:
      # HTTPS as entry point
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS
      traefik.ingress.kubernetes.io/router.tls: "true"
      # Enable cert-manager to create automatically the SSL certificate and store in Secret
      cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
      cert-manager.io/common-name: vocalog-parse-test.miku.software
    hosts:
      - host: vocalog-parse-test.miku.software
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: vocalog-parse-test-tls
        hosts:
          - vocalog-parse-test.miku.software

mongodb:
  global:
    defaultStorageClass: azurefile-csi
  persistence:
    enabled: true
    storageClass: azurefile-csi
    size: 8Gi
  architecture: replicaset
  replicaCount: 2
  serviceAccount:
    create: true
  automountServiceAccountToken: true
  rbac:
    create: true
  auth:
    usernames:
      - "admin"
    databases:
      - "parse"
    existingSecret: mongo-password-secret
